# Generated by Django 3.1.7 on 2021-04-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_app', '0003_playlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='youtube_id',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
